# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataserver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61taserver.proto\x12\x08lightdfs\"%\n\x08response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1c\n\x0cmkdirRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x19\n\tlsRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\")\n\nlsResponse\x12\r\n\x05\x66iles\x18\x01 \x03(\t\x12\x0c\n\x04\x64irs\x18\x02 \x03(\t\"\x19\n\trmRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"+\n\ruploadRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1f\n\x0f\x64ownloadRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\" \n\x10\x64ownloadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1a\n\npwdRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1b\n\x0bpwdResponse\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1b\n\x0bsyncRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1c\n\x0csyncResponse\x12\x0c\n\x04path\x18\x01 \x01(\t2\x90\x03\n\ndataserver\x12\x35\n\x05mkdir\x12\x16.lightdfs.mkdirRequest\x1a\x12.lightdfs.response\"\x00\x12\x31\n\x02ls\x12\x13.lightdfs.lsRequest\x1a\x14.lightdfs.lsResponse\"\x00\x12/\n\x02rm\x12\x13.lightdfs.rmRequest\x1a\x12.lightdfs.response\"\x00\x12\x37\n\x06upload\x12\x17.lightdfs.uploadRequest\x1a\x12.lightdfs.response\"\x00\x12\x43\n\x08\x64ownload\x12\x19.lightdfs.downloadRequest\x1a\x1a.lightdfs.downloadResponse\"\x00\x12\x34\n\x03pwd\x12\x14.lightdfs.pwdRequest\x1a\x15.lightdfs.pwdResponse\"\x00\x12\x33\n\x04sync\x12\x15.lightdfs.syncRequest\x1a\x12.lightdfs.response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataserver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=30
  _RESPONSE._serialized_end=67
  _MKDIRREQUEST._serialized_start=69
  _MKDIRREQUEST._serialized_end=97
  _LSREQUEST._serialized_start=99
  _LSREQUEST._serialized_end=124
  _LSRESPONSE._serialized_start=126
  _LSRESPONSE._serialized_end=167
  _RMREQUEST._serialized_start=169
  _RMREQUEST._serialized_end=194
  _UPLOADREQUEST._serialized_start=196
  _UPLOADREQUEST._serialized_end=239
  _DOWNLOADREQUEST._serialized_start=241
  _DOWNLOADREQUEST._serialized_end=272
  _DOWNLOADRESPONSE._serialized_start=274
  _DOWNLOADRESPONSE._serialized_end=306
  _PWDREQUEST._serialized_start=308
  _PWDREQUEST._serialized_end=334
  _PWDRESPONSE._serialized_start=336
  _PWDRESPONSE._serialized_end=363
  _SYNCREQUEST._serialized_start=365
  _SYNCREQUEST._serialized_end=392
  _SYNCRESPONSE._serialized_start=394
  _SYNCRESPONSE._serialized_end=422
  _DATASERVER._serialized_start=425
  _DATASERVER._serialized_end=825
# @@protoc_insertion_point(module_scope)
