# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dataserver_pb2 as dataserver__pb2


class DataServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFile = channel.unary_unary(
                '/lightdfs.DataServer/CreateFile',
                request_serializer=dataserver__pb2.CreateFileRequest.SerializeToString,
                response_deserializer=dataserver__pb2.BaseResponse.FromString,
                )
        self.CreateDirectory = channel.unary_unary(
                '/lightdfs.DataServer/CreateDirectory',
                request_serializer=dataserver__pb2.CreateDirectoryRequest.SerializeToString,
                response_deserializer=dataserver__pb2.BaseResponse.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/lightdfs.DataServer/DeleteFile',
                request_serializer=dataserver__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=dataserver__pb2.BaseResponse.FromString,
                )
        self.RenameFile = channel.unary_unary(
                '/lightdfs.DataServer/RenameFile',
                request_serializer=dataserver__pb2.RenameFileRequest.SerializeToString,
                response_deserializer=dataserver__pb2.BaseResponse.FromString,
                )
        self.ReadFile = channel.unary_unary(
                '/lightdfs.DataServer/ReadFile',
                request_serializer=dataserver__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=dataserver__pb2.ReadFileResponse.FromString,
                )
        self.UploadFile = channel.stream_unary(
                '/lightdfs.DataServer/UploadFile',
                request_serializer=dataserver__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=dataserver__pb2.BaseResponse.FromString,
                )
        self.UploadFileWithoutSync = channel.stream_unary(
                '/lightdfs.DataServer/UploadFileWithoutSync',
                request_serializer=dataserver__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=dataserver__pb2.BaseResponse.FromString,
                )
        self.DownloadFile = channel.unary_stream(
                '/lightdfs.DataServer/DownloadFile',
                request_serializer=dataserver__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=dataserver__pb2.DownloadFileResponse.FromString,
                )
        self.CopyFile = channel.unary_unary(
                '/lightdfs.DataServer/CopyFile',
                request_serializer=dataserver__pb2.CopyFileRequest.SerializeToString,
                response_deserializer=dataserver__pb2.BaseResponse.FromString,
                )
        self.WriteFile = channel.stream_unary(
                '/lightdfs.DataServer/WriteFile',
                request_serializer=dataserver__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=dataserver__pb2.BaseResponse.FromString,
                )
        self.OpenFile = channel.unary_unary(
                '/lightdfs.DataServer/OpenFile',
                request_serializer=dataserver__pb2.OpenFileRequest.SerializeToString,
                response_deserializer=dataserver__pb2.BaseResponse.FromString,
                )
        self.NotifyOffline = channel.unary_unary(
                '/lightdfs.DataServer/NotifyOffline',
                request_serializer=dataserver__pb2.NotifyOfflineRequest.SerializeToString,
                response_deserializer=dataserver__pb2.BaseResponse.FromString,
                )


class DataServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFile(self, request, context):
        """创建文件，对应touch命令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDirectory(self, request, context):
        """创建文件夹，对应mkdir命令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """删除文件，对应rm命令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameFile(self, request, context):
        """重命名或移动文件，对应mv命令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """读取文件，对应cat命令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """上传文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFileWithoutSync(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """下载文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyFile(self, request, context):
        """复制文件或文件夹
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request_iterator, context):
        """写文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenFile(self, request, context):
        """打开文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyOffline(self, request, context):
        """通知下线
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFile,
                    request_deserializer=dataserver__pb2.CreateFileRequest.FromString,
                    response_serializer=dataserver__pb2.BaseResponse.SerializeToString,
            ),
            'CreateDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDirectory,
                    request_deserializer=dataserver__pb2.CreateDirectoryRequest.FromString,
                    response_serializer=dataserver__pb2.BaseResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=dataserver__pb2.DeleteFileRequest.FromString,
                    response_serializer=dataserver__pb2.BaseResponse.SerializeToString,
            ),
            'RenameFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameFile,
                    request_deserializer=dataserver__pb2.RenameFileRequest.FromString,
                    response_serializer=dataserver__pb2.BaseResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=dataserver__pb2.ReadFileRequest.FromString,
                    response_serializer=dataserver__pb2.ReadFileResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=dataserver__pb2.UploadFileRequest.FromString,
                    response_serializer=dataserver__pb2.BaseResponse.SerializeToString,
            ),
            'UploadFileWithoutSync': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFileWithoutSync,
                    request_deserializer=dataserver__pb2.UploadFileRequest.FromString,
                    response_serializer=dataserver__pb2.BaseResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=dataserver__pb2.DownloadFileRequest.FromString,
                    response_serializer=dataserver__pb2.DownloadFileResponse.SerializeToString,
            ),
            'CopyFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyFile,
                    request_deserializer=dataserver__pb2.CopyFileRequest.FromString,
                    response_serializer=dataserver__pb2.BaseResponse.SerializeToString,
            ),
            'WriteFile': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=dataserver__pb2.UploadFileRequest.FromString,
                    response_serializer=dataserver__pb2.BaseResponse.SerializeToString,
            ),
            'OpenFile': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenFile,
                    request_deserializer=dataserver__pb2.OpenFileRequest.FromString,
                    response_serializer=dataserver__pb2.BaseResponse.SerializeToString,
            ),
            'NotifyOffline': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyOffline,
                    request_deserializer=dataserver__pb2.NotifyOfflineRequest.FromString,
                    response_serializer=dataserver__pb2.BaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lightdfs.DataServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.DataServer/CreateFile',
            dataserver__pb2.CreateFileRequest.SerializeToString,
            dataserver__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.DataServer/CreateDirectory',
            dataserver__pb2.CreateDirectoryRequest.SerializeToString,
            dataserver__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.DataServer/DeleteFile',
            dataserver__pb2.DeleteFileRequest.SerializeToString,
            dataserver__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RenameFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.DataServer/RenameFile',
            dataserver__pb2.RenameFileRequest.SerializeToString,
            dataserver__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.DataServer/ReadFile',
            dataserver__pb2.ReadFileRequest.SerializeToString,
            dataserver__pb2.ReadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/lightdfs.DataServer/UploadFile',
            dataserver__pb2.UploadFileRequest.SerializeToString,
            dataserver__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadFileWithoutSync(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/lightdfs.DataServer/UploadFileWithoutSync',
            dataserver__pb2.UploadFileRequest.SerializeToString,
            dataserver__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/lightdfs.DataServer/DownloadFile',
            dataserver__pb2.DownloadFileRequest.SerializeToString,
            dataserver__pb2.DownloadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CopyFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.DataServer/CopyFile',
            dataserver__pb2.CopyFileRequest.SerializeToString,
            dataserver__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/lightdfs.DataServer/WriteFile',
            dataserver__pb2.UploadFileRequest.SerializeToString,
            dataserver__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.DataServer/OpenFile',
            dataserver__pb2.OpenFileRequest.SerializeToString,
            dataserver__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyOffline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.DataServer/NotifyOffline',
            dataserver__pb2.NotifyOfflineRequest.SerializeToString,
            dataserver__pb2.BaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
