# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataServer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DataServer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x44\x61taServer.proto\"+\n\x0bupload_file\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\"\x19\n\tfile_path\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x15\n\x05reply\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\"\x1c\n\nfileStream\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x18\n\x08\x66ileList\x12\x0c\n\x04list\x18\x01 \x01(\t2\x84\x02\n\rstorageServer\x12%\n\tsynUpload\x12\x0c.upload_file\x1a\x06.reply\"\x00(\x01\x12\"\n\x06upload\x12\x0c.upload_file\x1a\x06.reply\"\x00(\x01\x12\'\n\x08\x64ownload\x12\n.file_path\x1a\x0b.fileStream\"\x00\x30\x01\x12\x1d\n\x02ls\x12\n.file_path\x1a\t.fileList\"\x00\x12\x1d\n\x05mkdir\x12\n.file_path\x1a\x06.reply\"\x00\x12!\n\tsynDelete\x12\n.file_path\x1a\x06.reply\"\x00\x12\x1e\n\x06\x64\x65lete\x12\n.file_path\x1a\x06.reply\"\x00\x62\x06proto3'
)




_UPLOAD_FILE = _descriptor.Descriptor(
  name='upload_file',
  full_name='upload_file',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='upload_file.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buffer', full_name='upload_file.buffer', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=63,
)


_FILE_PATH = _descriptor.Descriptor(
  name='file_path',
  full_name='file_path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='file_path.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=90,
)


_REPLY = _descriptor.Descriptor(
  name='reply',
  full_name='reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='done', full_name='reply.done', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=113,
)


_FILESTREAM = _descriptor.Descriptor(
  name='fileStream',
  full_name='fileStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='fileStream.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=143,
)


_FILELIST = _descriptor.Descriptor(
  name='fileList',
  full_name='fileList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='fileList.list', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['upload_file'] = _UPLOAD_FILE
DESCRIPTOR.message_types_by_name['file_path'] = _FILE_PATH
DESCRIPTOR.message_types_by_name['reply'] = _REPLY
DESCRIPTOR.message_types_by_name['fileStream'] = _FILESTREAM
DESCRIPTOR.message_types_by_name['fileList'] = _FILELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

upload_file = _reflection.GeneratedProtocolMessageType('upload_file', (_message.Message,), {
  'DESCRIPTOR' : _UPLOAD_FILE,
  '__module__' : 'DataServer_pb2'
  # @@protoc_insertion_point(class_scope:upload_file)
  })
_sym_db.RegisterMessage(upload_file)

file_path = _reflection.GeneratedProtocolMessageType('file_path', (_message.Message,), {
  'DESCRIPTOR' : _FILE_PATH,
  '__module__' : 'DataServer_pb2'
  # @@protoc_insertion_point(class_scope:file_path)
  })
_sym_db.RegisterMessage(file_path)

reply = _reflection.GeneratedProtocolMessageType('reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'DataServer_pb2'
  # @@protoc_insertion_point(class_scope:reply)
  })
_sym_db.RegisterMessage(reply)

fileStream = _reflection.GeneratedProtocolMessageType('fileStream', (_message.Message,), {
  'DESCRIPTOR' : _FILESTREAM,
  '__module__' : 'DataServer_pb2'
  # @@protoc_insertion_point(class_scope:fileStream)
  })
_sym_db.RegisterMessage(fileStream)

fileList = _reflection.GeneratedProtocolMessageType('fileList', (_message.Message,), {
  'DESCRIPTOR' : _FILELIST,
  '__module__' : 'DataServer_pb2'
  # @@protoc_insertion_point(class_scope:fileList)
  })
_sym_db.RegisterMessage(fileList)



_STORAGESERVER = _descriptor.ServiceDescriptor(
  name='storageServer',
  full_name='storageServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=172,
  serialized_end=432,
  methods=[
  _descriptor.MethodDescriptor(
    name='synUpload',
    full_name='storageServer.synUpload',
    index=0,
    containing_service=None,
    input_type=_UPLOAD_FILE,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='upload',
    full_name='storageServer.upload',
    index=1,
    containing_service=None,
    input_type=_UPLOAD_FILE,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='download',
    full_name='storageServer.download',
    index=2,
    containing_service=None,
    input_type=_FILE_PATH,
    output_type=_FILESTREAM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ls',
    full_name='storageServer.ls',
    index=3,
    containing_service=None,
    input_type=_FILE_PATH,
    output_type=_FILELIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='mkdir',
    full_name='storageServer.mkdir',
    index=4,
    containing_service=None,
    input_type=_FILE_PATH,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='synDelete',
    full_name='storageServer.synDelete',
    index=5,
    containing_service=None,
    input_type=_FILE_PATH,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='storageServer.delete',
    index=6,
    containing_service=None,
    input_type=_FILE_PATH,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGESERVER)

DESCRIPTOR.services_by_name['storageServer'] = _STORAGESERVER

# @@protoc_insertion_point(module_scope)
