# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nameserver_pb2 as nameserver__pb2


class NameserverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDataServer = channel.unary_unary(
                '/lightdfs.Nameserver/RegisterDataServer',
                request_serializer=nameserver__pb2.DataServerInfo.SerializeToString,
                response_deserializer=nameserver__pb2.Response.FromString,
                )
        self.GetDataServerList = channel.unary_unary(
                '/lightdfs.Nameserver/GetDataServerList',
                request_serializer=nameserver__pb2.empty.SerializeToString,
                response_deserializer=nameserver__pb2.GetDataServerListResponse.FromString,
                )
        self.LogoutDataServer = channel.unary_unary(
                '/lightdfs.Nameserver/LogoutDataServer',
                request_serializer=nameserver__pb2.DataServerInfo.SerializeToString,
                response_deserializer=nameserver__pb2.Response.FromString,
                )
        self.RegisterUser = channel.unary_unary(
                '/lightdfs.Nameserver/RegisterUser',
                request_serializer=nameserver__pb2.RegisterRequest.SerializeToString,
                response_deserializer=nameserver__pb2.Response.FromString,
                )
        self.Login = channel.unary_unary(
                '/lightdfs.Nameserver/Login',
                request_serializer=nameserver__pb2.LoginRequest.SerializeToString,
                response_deserializer=nameserver__pb2.Response.FromString,
                )
        self.Logout = channel.unary_unary(
                '/lightdfs.Nameserver/Logout',
                request_serializer=nameserver__pb2.LogoutRequest.SerializeToString,
                response_deserializer=nameserver__pb2.Response.FromString,
                )
        self.LockFile = channel.unary_unary(
                '/lightdfs.Nameserver/LockFile',
                request_serializer=nameserver__pb2.LockFileRequest.SerializeToString,
                response_deserializer=nameserver__pb2.Response.FromString,
                )
        self.UnlockFile = channel.unary_unary(
                '/lightdfs.Nameserver/UnlockFile',
                request_serializer=nameserver__pb2.UnlockFileRequest.SerializeToString,
                response_deserializer=nameserver__pb2.Response.FromString,
                )
        self.CheckFilePermission = channel.unary_unary(
                '/lightdfs.Nameserver/CheckFilePermission',
                request_serializer=nameserver__pb2.CheckFilePermissionRequest.SerializeToString,
                response_deserializer=nameserver__pb2.Response.FromString,
                )


class NameserverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDataServer(self, request, context):
        """注册数据服务器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataServerList(self, request, context):
        """获取数据服务器列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutDataServer(self, request, context):
        """下线数据服务器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterUser(self, request, context):
        """注册用户
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """登录
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """登出
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockFile(self, request, context):
        """文件锁
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckFilePermission(self, request, context):
        """检查文件权限
        检查缓存
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameserverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDataServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDataServer,
                    request_deserializer=nameserver__pb2.DataServerInfo.FromString,
                    response_serializer=nameserver__pb2.Response.SerializeToString,
            ),
            'GetDataServerList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataServerList,
                    request_deserializer=nameserver__pb2.empty.FromString,
                    response_serializer=nameserver__pb2.GetDataServerListResponse.SerializeToString,
            ),
            'LogoutDataServer': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutDataServer,
                    request_deserializer=nameserver__pb2.DataServerInfo.FromString,
                    response_serializer=nameserver__pb2.Response.SerializeToString,
            ),
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=nameserver__pb2.RegisterRequest.FromString,
                    response_serializer=nameserver__pb2.Response.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=nameserver__pb2.LoginRequest.FromString,
                    response_serializer=nameserver__pb2.Response.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=nameserver__pb2.LogoutRequest.FromString,
                    response_serializer=nameserver__pb2.Response.SerializeToString,
            ),
            'LockFile': grpc.unary_unary_rpc_method_handler(
                    servicer.LockFile,
                    request_deserializer=nameserver__pb2.LockFileRequest.FromString,
                    response_serializer=nameserver__pb2.Response.SerializeToString,
            ),
            'UnlockFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockFile,
                    request_deserializer=nameserver__pb2.UnlockFileRequest.FromString,
                    response_serializer=nameserver__pb2.Response.SerializeToString,
            ),
            'CheckFilePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckFilePermission,
                    request_deserializer=nameserver__pb2.CheckFilePermissionRequest.FromString,
                    response_serializer=nameserver__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lightdfs.Nameserver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Nameserver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDataServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.Nameserver/RegisterDataServer',
            nameserver__pb2.DataServerInfo.SerializeToString,
            nameserver__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataServerList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.Nameserver/GetDataServerList',
            nameserver__pb2.empty.SerializeToString,
            nameserver__pb2.GetDataServerListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogoutDataServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.Nameserver/LogoutDataServer',
            nameserver__pb2.DataServerInfo.SerializeToString,
            nameserver__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.Nameserver/RegisterUser',
            nameserver__pb2.RegisterRequest.SerializeToString,
            nameserver__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.Nameserver/Login',
            nameserver__pb2.LoginRequest.SerializeToString,
            nameserver__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.Nameserver/Logout',
            nameserver__pb2.LogoutRequest.SerializeToString,
            nameserver__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LockFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.Nameserver/LockFile',
            nameserver__pb2.LockFileRequest.SerializeToString,
            nameserver__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnlockFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.Nameserver/UnlockFile',
            nameserver__pb2.UnlockFileRequest.SerializeToString,
            nameserver__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckFilePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lightdfs.Nameserver/CheckFilePermission',
            nameserver__pb2.CheckFilePermissionRequest.SerializeToString,
            nameserver__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
